# Generated by Django 4.2.5 on 2023-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('registration', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('desig', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=5)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=200)),
                ('grevience', models.CharField(max_length=500)),
            ],
        ),
    ]
