# Generated by Django 3.2.18 on 2023-10-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellorModel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('registration', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('counsellorId', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
