# Generated by Django 3.2.18 on 2023-10-03 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_counsellormodel_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
