# Generated by Django 5.0.1 on 2024-06-24 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='founditems',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lostitems',
            name='image',
        ),
    ]
