# Generated by Django 5.0.1 on 2024-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_remove_founditems_image_remove_lostitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='founditems/'),
        ),
        migrations.AddField(
            model_name='lostitems',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='lostitems/'),
        ),
    ]
