# Generated by Django 5.0.1 on 2024-06-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_founditems_image_lostitems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditems',
            name='contact',
            field=models.BigIntegerField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lostitems',
            name='contact',
            field=models.BigIntegerField(default=None, max_length=100),
        ),
    ]
